handlers:
  - sink: "ext://sys.stdout"
    level: "INFO"
    colorize: true
    format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> [<level>{level}</level>] <cyan>{name}</cyan>: {message} | Extra: {extra}"

  - sink: "log/app.jsonl"
    level: "INFO"
    rotation: "10 MB"
    retention: 5
    json: true 

  - sink: telegram
    level: "ERROR"

activation:
  - ["aiogram.event", "WARNING"]
  - ["aiogram.dispatcher", "INFO"]