parse_mode: html # / markdown / None

responses:
  public:
    start: >
      Привет, {first_name}! 👋 Я помогу найти ответ на ваш вопрос. 
      Просто напишите мне, выберите один из частых вопросов ниже 
      или используйте /help, чтобы связаться с поддержкой.
    failed: "{exception}. Попробуйте сформулировать иначе и спросить еще раз"
    error: >
      ❌ Произошла непредвиденная ошибка!
      Мы уже работаем над исправлением. Пожалуйста, попробуйте позже.
    banned: 'Ваш доступ к боту ограничен. Если вы считаете, что это произошло по ошибке, свяжитесь с нами: <a href="https://t.me/fincubes">t.me/fincubes</a> или <a href="mailto:mail@fincubes.ru">mail@fincubes.ru</a>.'
    rate_limited: "Слишком много запросов. Попробуйте снова чуть позже."

exceptions:
  search:
    not_found: "Кажется, мне не удалось распознать вопрос"

process:
  question:
    msg_question_text_invalid: "Пожалуйста, пришлите ваш вопрос простым текстовым сообщением"
    cmd_question_text_invalid: "Пожалуйста, укажите текст вопроса сразу после команды"

validation:
  question:
    question_text_long: "Текст вопроса слишком длинный"
