parse_mode: html # / markdown / null


responses: # Messages sent to regular users
  public:
    start: > # Welcome message < message
      Hello, {first_name}! I will help you find the answer — just send a question
      or choose one of the most popular ones below!
    # When question processing fails < message
    failed: "{exception}. Try to reformulate it and ask again"
    error: > # < Internal error notification < message
      {emoji.status.failed} Unexcepted internal error!
      We are already fixing it. Try to retry
    banned: "{emoji.status.failed} You have been added to the blacklist and can no longer use this bot." #  < message
    rate_limited: "Too many requests. Please try again a bit later." #  < message
    # "message" variable representes id (user id), first_name,
    # last_name, username, full_name, date

  admin: # Messages sent to administrators, organized by entity:
    invalid: "{emoji.status.warning} {exception}. Retry or back" # < exception
    expired: "The time for the operation has expired. Start over"
    access_denied: "Access denied: {exception}" # < exception
    ban: # < id, username
      banned: "{emoji.status.successful} User {identity} has been banned."
      unbanned: "{emoji.status.successful} User {identity} has been unbanned."
    user: # User flows
      enter: 
        identity: "{emoji.action.enter} Enter the telegram id, share contact or forward a message"
        username: "{emoji.action.enter} Enter a username"
        role: "{emoji.action.select} Select a role:"
      creation: 
        confirm: | # < user
          {emoji.action.select} Confirm creation?
          {user}
        successful: | # < user
          {emoji.status.successful} User has been successfully created:
          {user}
      finding:
        successful: | # < user
          {emoji.status.successful} The user has been successfully found in the database:
          {user}
        partially_found: | # < user
          {emoji.status.warning} The user has been partially found but missing in the database:
          {user}
      update:
        confirm: | # < user
          {emoji.action.select} Update this user?
          {user}
        select_field: | # < user
          {user}
          {emoji.action.select} Select the field to edit:
        successful: | # < user
          {emoji.status.successful} The user has been successfully updated:
          {user}
        access_denied: "You can’t update an admin user."
      deletion:
        confirm: | # < user 
          {emoji.action.select} Confirm deletion?
          {user}
        successful: | # < user
          {emoji.status.successful} Next user has been successfully deleted:
          {user}
        access_denied: "You can’t delete an admin user."
      listing:
          successful: | # < content - table of users
            {emoji.action.list} User list: {page}/{max_page}
            <pre>{content}</pre>
          not_found: "{emoji.action.list} No users found in the system"

    question: # Question flows
      enter:
        id: "{emoji.action.enter} Enter the question id"
        question_text: "{emoji.action.enter} Enter a question text"
        answer_text: "{emoji.action.enter} Enter a answer text"
        rating: "{emoji.action.enter} Enter a rating"
      creation:
        confirm: | # < question
          {emoji.action.select} Confirm creation?
          {question}
        successful: | # < question
          {emoji.status.successful} Question has been successfully created:
          {question}
        similar: | # When similar question exists < question
          {emoji.status.warning} A similar question already exists:
          {question}
          {emoji.action.select} Confirm creation?
      finding:
        successful: | # < question
          {emoji.status.successful} The question has been successfully found:
          {question}
      update:
        confirm: | # < question
          {emoji.action.select} Update this question?
          {question}
        select_field: | # < question
          {question}
          {emoji.action.select} Select the field to edit:
        # For embedding recalculation
        confirm_recompute: "{emoji.action.select} Recompute embedding?"
        successful: |
          {emoji.status.successful} The question has been successfully updated:
          {question}
      deletion:
        confirm: | # < question
          {emoji.action.select} Confirm deletion?
          {question}
        successful: | # < question
          {emoji.status.successful} Next question has been successfully deleted:
          {question}
      listing:
        successful: | # < content - table of question
          {emoji.action.list} Question list: {page}/{max_page}
          <pre>{content}</pre>
        not_found: "{emoji.action.list} No questions found in the system"

    settings:
      main: "{emoji.menu.settings} Settings"
      user: "{emoji.menu.user} User"
      question: "{emoji.menu.question} Question"

    misc:
      goto:
        go: "Go!"
        confirm: "{emoji.action.select} Go to <code>{content}</code>?" # < content - path
      state:
        serialization: '<pre><code class="json">{content}</code></pre>' # < content - state
        argument: "<code>{content}</code>" # < content - argument formatting

exceptions: # Error messages shown to user
  search:
    not_found: "It seems that we failed to understand the question"

  user:
    not_found: "{emoji.status.failed} User {identity} not found" # < identity
    already_exists: "A user with the ID {id} or the username {username} already exists" # < id, username

  question:
    not_found: "{emoji.status.failed} Question {id} not found" # < id
    embedding_failed: "Failed to compute vector representation of question"

  misc:
    invalid_path: "Failed to go: The path is not set"
    invalid_changes: "Pass changes with the <code>key=value</code> format"
    invalid_argument: "Invalid argument: {exception}" # < exception

process: # Messages shown during input processing
  common: # Invalid pagination input
    page_invalid: "Message type is invalid"

  user: # Invalid user input formats
    contact_invalid: "The account is hidden or the user is not registered"
    identity_invalid: "Please send a simple text message with ID, contact or forward the message"
    username_invalid: "Please send a simple text message with the username"
    role_invalid: "Please send a simple text message with the role or choose one from the list"

  question: # Invalid question input formats
    id_invalid: "Please send a simple text message with ID"
    msg_question_text_invalid: "Please send a simple text message with the question" # + -(app.handlers.public)
    cmd_question_text_invalid: "Please specify the question text after the command" # -(app.handlers.public)
    answer_text_invalid: "Please send a simple text message with the answer to the question"
    rating_invalid: "Please send a simple text message with the rating"

validation: # Messages for data integrity validation
  common: # Pagination errors
    page_invalid: "Page is invalid"
    page_negative: "Page cannot be negative"

  user: # Username length/symbol validation
    id_invalid: "ID is invalid"
    username_short: "The username is too short"
    username_long: "The username is too long"
    username_unexcepted_symbols: "The username has unexcepted symbols"
    role_unexcepted: "An unexpected role"
    
  question: # Text length and rating validation
    id_invalid: "ID is invalid"
    question_text_long: "The question text is too long"
    answer_text_long: "The answer text is too long"
    rating_incorrect: "Rating is incorrect"

format: # Templates for consistent data presentation
  field:
    id: "<code>{id}</code>" # < id
    exception: "{emoji.status.failed} {exception}" # < exception
    question_text: "{question_text}" # < question_text
    answer_text: "{answer_text}" # < answer_text
    rating: "{rating}" # < rating
    username: "<code>@{username}</code>" # < username
    user_link: "<a href='tg://user?id={id}'>@{username}</a>" # < id, username
    user_role: "<b>{user_role}</b>" # < role
    date: "%d.%m.%Y %H:%M"

  fallback: # Fallback message data -(app.utils.format)
    last_name: ""
    username: ""
    exception: "Unexcepted error"
    
  user: # Complete user representation
      id: "ID: {id}" # < id
      username: "Username: {username}" # < username
      user_link: "Link: {user_link}" # < user_link
      user_role: "Role: {user_role}" # < user_role
      
  question: # Complete question representation
    id: "{emoji.symbol.index} {id} Question:" # < id
    question_text: "{emoji.symbol.question} Text: {question_text}" # < question_text
    answer_text: "{emoji.symbol.answer} Answer: {answer_text}" # < answer_text
    rating: "{emoji.symbol.rating} Rating: {rating}" # < rating
    recomputed: "{emoji.symbol.embedding} Embedding will be recomputed" 
    not_recomputed: "{emoji.symbol.embedding} Embedding will NOT be recomputed"

  edit: # Shows changes during edit operations
    unedited: "{old}" # < old - original value
    edited: "{old} {emoji.symbol.change} {new}" # < old, new - original and new values

  canceled: | # < old - original of the canceled message
      {old}
      {emoji.nav.cancel} CANCELED {emoji.nav.cancel}

button:
  question: 
    question_text: "Question Text"
    answer_text: "Answer Text"
    rating: "Rating"
    found: "Found ({id})" # < id

  user:
    username: "Username"
    role: "Role"
    found: "Found ({identity})" # < identity
    you: "You ({identity})" # < identity

  settings:
    user: "{emoji.menu.user} Users"
    question: "{emoji.menu.question} Questions"

  common:
    close: "{emoji.nav.close} Close"
    back: "{emoji.nav.back} Back"
    cancel: "{emoji.nav.cancel} Cancel"
    create: "{emoji.action.create} Create"
    get: "{emoji.action.get} Get"
    update: "{emoji.action.update} Update"
    delete: "{emoji.action.delete} Delete"
    list: "{emoji.action.list} List"
    confirm: "{emoji.action.confirm}"
    reject: "{emoji.action.reject}"
    save: "{emoji.action.save}"
    discard: "{emoji.action.discard}"
    previous: "{emoji.nav.left} Previous"
    next: "Next {emoji.nav.right}"
    ascending: "{emoji.nav.up}"
    descending: "{emoji.nav.down}"
    empty: "{emoji.action.empty} Empty"
