SETTINGS = "settings"

CREATE = "create"
GET = "get"
UPDATE = "update"
DELETE = "delete"

USERS = (SETTINGS, f"{SETTINGS}.users")

USERS_CREATE = (USERS[1], f"{USERS[1]}.{CREATE}")
USERS_GET = (USERS[1], f"{USERS[1]}.{GET}")
USERS_UPDATE = (USERS[1], f"{USERS[1]}.{UPDATE}")
USERS_DELETE = (USERS[1], f"{USERS[1]}.{DELETE}")

QUESTIONS = (SETTINGS, f"{SETTINGS}.questions")

QUESTIONS_CREATE = (QUESTIONS[1], f"{QUESTIONS[1]}.{CREATE}")
QUESTIONS_GET = (QUESTIONS[1], f"{QUESTIONS[1]}.{GET}")
QUESTIONS_UPDATE = (QUESTIONS[1], f"{QUESTIONS[1]}.{UPDATE}")
QUESTIONS_DELETE = (QUESTIONS[1], f"{QUESTIONS[1]}.{DELETE}")
