SETTINGS = "settings"

CREATE = "create"
GET = "get"
UPDATE = "update"
DELETE = "delete"
LIST = "list"

USERS = (SETTINGS, f"{SETTINGS}.users")

USERS_CREATE = (USERS[1], f"{USERS[1]}.{CREATE}")
USERS_GET = (USERS[1], f"{USERS[1]}.{GET}")
USERS_UPDATE = (USERS[1], f"{USERS[1]}.{UPDATE}")
USERS_DELETE = (USERS[1], f"{USERS[1]}.{DELETE}")
USERS_LIST = (USERS[1], f"{USERS[1]}.{LIST}")

QUESTIONS = (SETTINGS, f"{SETTINGS}.questions")

QUESTIONS_CREATE = (QUESTIONS[1], f"{QUESTIONS[1]}.{CREATE}")
QUESTIONS_GET = (QUESTIONS[1], f"{QUESTIONS[1]}.{GET}")
QUESTIONS_UPDATE = (QUESTIONS[1], f"{QUESTIONS[1]}.{UPDATE}")
QUESTIONS_DELETE = (QUESTIONS[1], f"{QUESTIONS[1]}.{DELETE}")
QUESTIONS_LIST = (QUESTIONS[1], f"{QUESTIONS[1]}.{LIST}")

TICKETS = (SETTINGS, f"{SETTINGS}.tickets")

TICKETS_CREATE = (TICKETS[1], f"{TICKETS[1]}.{CREATE}")
TICKETS_GET = (TICKETS[1], f"{TICKETS[1]}.{GET}")
TICKETS_UPDATE = (TICKETS[1], f"{TICKETS[1]}.{UPDATE}")
TICKETS_DELETE = (TICKETS[1], f"{TICKETS[1]}.{DELETE}")
TICKETS_LIST = (TICKETS[1], f"{TICKETS[1]}.{LIST}")
