SETTINGS = "settings"

CREATE = "create"
GET = "get"
UPDATE = "update"
DELETE = "delete"

USERS = (SETTINGS, f"{SETTINGS}.users")

USERS_CREATE = (USERS, f"{USERS}.{CREATE}")
USERS_GET = (USERS, f"{USERS}.{GET}")
USERS_UPDATE = (USERS, f"{USERS}.{UPDATE}")
USERS_DELETE = (USERS, f"{USERS}.{DELETE}")

QUESTIONS = (SETTINGS, f"{SETTINGS}.questions")

QUESTIONS_CREATE = (QUESTIONS, f"{QUESTIONS}.{CREATE}")
QUESTIONS_GET = (QUESTIONS, f"{QUESTIONS}.{GET}")
QUESTIONS_UPDATE = (QUESTIONS, f"{QUESTIONS}.{UPDATE}")
QUESTIONS_DELETE = (QUESTIONS, f"{QUESTIONS}.{DELETE}")
